config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "site#home"
  resources :activities
  get '/home', to: 'site#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.fetch(:activity, {}).permit(:activity_type, :duration, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :update_allowed_parameters, if: :devise_controller?
  
    protected
  
    def update_allowed_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :email, :password)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :activity_type %>
    <%= form.select(:activity_type,[ 
    ['Walking', 'Walking'], 
    ['Running', 'Running'],
    ['Cycling', 'Cycling'],
    ['Swimming', 'Swimming'],
    ['Skating', 'Skating'],
    ['Hiking', 'Hiking'],
    ['Mountain Biking', 'Mountain Biking'],
    ['Circuit Training', 'Circuit Training'],
    ['Strength Training', 'Strength Training'],
    ['Snow Boarding', 'Snow Boarding']
    ]) 
    %>

    <%= javascript_pack_tag 'timer'%>

    <%# form.select_tag(:activity_type, options_for_select([['Walking', 'Walking'], ['Running', 'Running']], form.object.activity_type)) %>
    <%= form.date_field :date%>
    <%= form.number_field :duration, id: "activity_duration" %>

    <%# Create a modal class which autofocuses the activity duration timer%>
    <%#  %>
    <!-- Button to trigger Modal -->
    <button type="button" onClick="window.initialize()" class="btn btn-primary" data-toggle="modal" data-target="#grooveModal" data-backdrop="static" data-keyboard="false">
      Start Grooving
    </button>

    <!-- Modal -->
    <div class="modal fade" id="grooveModal" tabindex="-1" role="dialog" aria-labelledby="grooveModalTitle" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="grooveModalTitle">Hit the Stop button when done</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div id="timer_view">
              <label id="minutes">00</label>
              <label id="colon">:</label>
              <label id="seconds">00</label>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" onClick="window.start()" id="start" class="btn btn-danger">Start</button>
            <button type="button" onClick="window.stop()" id="stop" class="btn btn-danger">Stop</button>
            <button type="button" id="save" onClick="getDuration()" class="btn btn-primary" data-dismiss="modal">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    
    <br/>
    <%# check countdown timer gem%>
    <%= form.submit 'Log Activity' %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="activity-index">
  <!-- <p id="notice"><%= notice %></p> -->

  <h1>Activities</h1>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @activities.each do |activity| %>
        <tr>
          <td><%= link_to activity.activity_type, activity %></td>
          <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
          <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <div class="link-padding-index">
    <%= link_to 'New Activity', new_activity_path %>
  </div>

</div>

app/views/activities/new.html.erb
<div class="new_activity_design">
    <%= link_to 'Back', activities_path %>

    <h1 class="new">New Activity</h1>

    <%= render 'form', activity: @activity %>
    
</div>

app/views/activities/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h2> Details of this <%= @activity.activity_type%> Activity on <%= @activity.date%> </h2>
<p class="h1">
You were <%= @activity.activity_type %> for <%= @activity.duration/60 %> minutes : <%= @activity.duration%60 %> seconds
</p>

<div class="link-padding">
    <%= link_to 'Edit', edit_activity_path(@activity), class: 'link-padding' %>
    <%= link_to 'Back to Activity lists', activities_path, class: 'link-padding' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>          
    <nav class="navbar navbar-inverse navbar-expand-md">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href='/' class='navbar-brand'>
            <img class='homelogo'  src="/move-n-groove-logo.jpg" width="140" height="80" alt="site logo"/>
          </a>
        </div>
        <button type="button" class="navbar-toggler bg-dark" data-target="#myNavbar" data-toggle="collapse">
          <span class="navbar-toggler-icon bg-dark"></span>                
        </button> 
        <ul class="nav navbar-nav">
          <li class="btn btn-outline-primary btn-lg m-2 card"><%= link_to 'Home', root_path %></li>
          <li class="dropdown btn btn-outline-primary btn-lg card m-2"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Recent Events<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Page 1-1</a></li>
              <li><a href="#">Page 1-2</a></li>
              <li><a href="#">Page 1-3</a></li>
            </ul>
          </li>
          <li class="btn btn-outline-primary btn-lg card m-2"><a href="#" >About Us</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right right-bar">
          <% if !current_user %>            
            <li class="btn btn-outline-primary btn-lg card m-2"><%= link_to 'Sign up', new_user_registration_path %></li>
            <li class="btn btn-outline-primary btn-lg card m-2"><%= link_to 'Log in', new_user_session_path %></li>
          <% else %>
            <li class="btn btn-outline-primary btn-lg card m-2"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%# Jumbotron for the caption  %>
    <div class="jumbotron card card-image" style="background-image: url('/gradient1.jpg')">
      <div class="text-white text-center py-5 px-4">
        <h1 class="page-header text-white"> Good Health is the beauty of living </h1>
      </div>
    </div>    
  <!-- Alert Div -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <!-- Footer -->
    <div class="footer">

    </div>
  </body>
</html>

app/views/site/home.html.erb
<div class="home">

<% if !current_user %>
    <h1>Welcome to Move N Groove</h1>
    <p> Create a new account to beging to log your health activities </p>
<% else %>
    <h1>Welcome to Move N Groove dear <%= current_user.name %></h1>
    <div>
        <h3> To begin clikc the button below to select and log an activity </h3>
        <p class="btn btn-dark bg-white text-danger">
            <%= link_to 'Log an Activity', new_activity_path %>
        </p>
    </div>
<% end %>

</div>